export const CREATE_ISSUES_SUCCESS = "CREATE_ISSUES_SUCCESS";
export const CREATE_ISSUES_ERROR = "CREATE_ISSUES_ERROR";
export const BEFORE_STATE        = "BEFORE_STATE";
export const GET_ISSUES_SUCCESS  = "GET_ISSUES_SUCCESS";
export const GET_ISSUES_ERROR    = "GET_ISSUES_ERROR";